name: Build Darwin

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: charliemeyer-dots
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .#darwinConfigurations.darwin-personal.system
